### ISSUE TITLE
Non-exhaustive pattern match failure

### ISSUE THREAD

**Issue by takikawa** [stamourv/feature-profile#9] opened 2015-10-27 19:48 UTC
Run the following file to trigger:

````
#lang racket/base

(require ;errortrace/errortrace-lib
         profile
         feature-profile)

(define (do-profile mod)
  (profile (eval mod (make-base-namespace))))

(define (do-fsp mod)
  (feature-profile (eval mod (make-base-namespace))))

(define nm-path
  (collection-file-path "new-metrics.rkt" "typed-racket-test/succeed"))

(define nm-sexp
  (parameterize ([read-accept-lang #t]
                 [read-accept-reader #t])
    (with-input-from-file nm-path (λ () (read)))))

;(do-profile nm-sexp)
(do-fsp nm-sexp)
````

This is the error:

````
non-exhaustive pattern match (begin (define-values (lifted.0) (#%app module-name-fixup (#%app variable-reference->module-source/submod (#%variable-reference)) (#%app list))) (define-values (lifted.1) (#%app idX77 lifted.0)) (#%expression lifted.1))
  context...:
   /home/asumu/plt/racket-git/racket/share/pkgs/feature-profile/tree-walker.rkt:25:2
   get-sym
   /home/asumu/plt/racket-git/racket/collects/racket/promise.rkt:70:15
   /home/asumu/plt/racket-git/racket/collects/racket/private/more-scheme.rkt:265:2: call-with-exception-handler
   /home/asumu/plt/racket-git/racket/collects/racket/promise.rkt:38:2
   /home/asumu/plt/racket-git/racket/collects/racket/lazy-require.rkt:102:6
   ...rivate/parse.rkt:792:26
   /home/asumu/plt/racket-git/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/tc-setup.rkt:82:0: tc-module/full
   /home/asumu/plt/racket-git/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/typed-racket.rkt:24:4
````

**Comment by stamourv** [comment] 2015-10-28 20:40
I can reproduce this. And sure enough, it's in the activation pass. Ugh.

**Comment by stamourv** [comment] 2015-10-28 21:53
Ok, I think I may have an idea of what's going on.
It looks like the FSP is being fed phase-shifted code. Not sure where it's coming from though.
Will look into having the FSP skip phase-shifted code.

**Comment by stamourv** [comment] 2015-10-28 22:10
I pushed a fix for the immediate bug.
Your program still errors, but with a type error, this time. I'm not sure why, since new-metrics alone typechecks.
I'll look into it, hopefully tomorrow. If you have any ideas in the meantime, I'm all ears.

**Comment by takikawa** [comment] 2015-10-28 22:12
The type error is my fault. It's because you need `read-syntax` in there with the TR reader in order to get reader-based type annotations.

**Comment by takikawa** [comment] 2015-10-28 22:13
Here is a version that shouldn't error:

````
#lang racket/base

(require feature-profile
         typed-racket/typed-reader)

(define (do-profile mod)
  (feature-profile (eval mod (make-base-namespace))))

(define nm-path
  (collection-file-path "new-metrics.rkt" "typed-racket-test/succeed"))

(define nm-stx
  (parameterize ([read-accept-lang #t]
                 [read-accept-reader #t])
    (with-input-from-file nm-path (λ () (read-syntax 'bob (current-input-port))))))

(do-profile nm-stx)
````

**Comment by stamourv** [comment] 2015-10-28 22:17
Oh whew. That's a relief.
That tree walker is a nasty piece of code. Glad that the issue was not there. :)

**Comment by stamourv** [comment] 2015-10-28 22:18
(Oh, and yeah, your version indeed fixes the problem.)

**Closed by stamourv** 2015-10-28 22:17 UTC
